"""
Data models for Dimensio Visualization API

This module provides backward-compatible models and utilities,
now built on top of the new structured schemas.

For new code, prefer using schemas.py directly.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum
from datetime import datetime

# Import new schemas for internal use
from .schemas import (
    VisualizationType as NewVisualizationType,
    EventType,
    SpaceType,
    StepType
)


# ============================================================================
# Enumerations (Backward Compatible)
# ============================================================================

class VisualizationType(str, Enum):
    """
    Types of visualizations generated by Dimensio.

    Backward compatible with original API.
    Maps to new VisualizationType in schemas.py
    """
    SUMMARY = "compression_summary"
    RANGE_COMPRESSION = "range_compression"
    PARAMETER_IMPORTANCE = "parameter_importance"
    DIMENSION_EVOLUTION = "dimension_evolution"
    MULTI_TASK_HEATMAP = "multi_task_importance_heatmap"
    SOURCE_SIMILARITIES = "source_task_similarities"
    STRATEGIES_COMPARISON = "adaptive_strategies_comparison"


def classify_visualization_type(filename: str) -> Optional[VisualizationType]:
    """
    Classify visualization file by its name.

    Args:
        filename: Name of the visualization file (e.g., 'compression_summary.png')

    Returns:
        VisualizationType enum or None if not recognized
    """
    if filename == 'compression_summary.png':
        return VisualizationType.SUMMARY
    elif filename.startswith('range_compression_step_'):
        return VisualizationType.RANGE_COMPRESSION
    elif filename.startswith('parameter_importance_step_'):
        return VisualizationType.PARAMETER_IMPORTANCE
    elif filename == 'dimension_evolution.png':
        return VisualizationType.DIMENSION_EVOLUTION
    elif filename.startswith('multi_task_importance_heatmap'):
        return VisualizationType.MULTI_TASK_HEATMAP
    elif filename == 'source_task_similarities.png':
        return VisualizationType.SOURCE_SIMILARITIES
    elif filename == 'adaptive_strategies_comparison.png':
        return VisualizationType.STRATEGIES_COMPARISON
    return None


def extract_step_index(filename: str) -> Optional[int]:
    """
    Extract step index from visualization filename.

    Args:
        filename: Visualization filename (e.g., 'range_compression_step_2.png')

    Returns:
        Step index (0-based) or None if not found
    """
    import re
    match = re.search(r'_step_(\d+)\.png$', filename)
    if match:
        return int(match.group(1))
    return None


def get_visualization_data_requirements(viz_type: VisualizationType) -> Dict[str, Any]:
    """
    Get data requirements for each visualization type.

    Args:
        viz_type: Type of visualization

    Returns:
        Dictionary describing required data fields
    """
    requirements = {
        VisualizationType.SUMMARY: {
            'requires': ['initial_event', 'pipeline', 'spaces'],
            'optional': ['range_stats'],
            'description': '4-panel compression summary showing dimension reduction and ratios'
        },
        VisualizationType.RANGE_COMPRESSION: {
            'requires': ['step.compression_info'],
            'parameters': {'step_index': 'int'},
            'description': 'Parameter range compression visualization for a specific step'
        },
        VisualizationType.PARAMETER_IMPORTANCE: {
            'requires': ['step.importance_calculator', 'importance_scores'],
            'parameters': {'step_index': 'int', 'topk': 'int'},
            'description': 'Bar chart of top-k parameter importance scores'
        },
        VisualizationType.DIMENSION_EVOLUTION: {
            'requires': ['adaptive_events', 'iterations', 'dimensions'],
            'description': 'Line plot showing dimension changes across iterations'
        },
        VisualizationType.MULTI_TASK_HEATMAP: {
            'requires': ['multi_task_importance_data'],
            'parameters': {'step_index': 'int'},
            'description': 'Heatmap showing parameter importance across multiple tasks'
        },
        VisualizationType.SOURCE_SIMILARITIES: {
            'requires': ['source_task_data', 'similarity_scores'],
            'description': 'Bar chart showing source task similarities to target'
        },
        VisualizationType.STRATEGIES_COMPARISON: {
            'requires': ['multiple_experiments'],
            'description': 'Comparison of different adaptive strategies'
        }
    }

    return requirements.get(viz_type, {
        'requires': [],
        'description': 'Unknown visualization type'
    })
